/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as predictionMarketSettlementVaraEthSol from "./PredictionMarketSettlementVaraEth.sol";
export type { predictionMarketSettlementVaraEthSol };
export type { OutcomeToken } from "./OutcomeToken";
export type { PredictionMarketSettlement } from "./PredictionMarketSettlement";
export * as factories from "./factories";
export { OutcomeToken__factory } from "./factories/OutcomeToken__factory";
export { PredictionMarketSettlement__factory } from "./factories/PredictionMarketSettlement__factory";
export type { IVaraEthMirror } from "./PredictionMarketSettlementVaraEth.sol/IVaraEthMirror";
export { IVaraEthMirror__factory } from "./factories/PredictionMarketSettlementVaraEth.sol/IVaraEthMirror__factory";
export type { PredictionMarketSettlementVaraEth } from "./PredictionMarketSettlementVaraEth.sol/PredictionMarketSettlementVaraEth";
export { PredictionMarketSettlementVaraEth__factory } from "./factories/PredictionMarketSettlementVaraEth.sol/PredictionMarketSettlementVaraEth__factory";
