/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "./common";

export declare namespace PredictionMarketSettlement {
  export type MarketStruct = {
    creator: AddressLike;
    question: string;
    category: string;
    endTime: BigNumberish;
    status: BigNumberish;
    outcome: BigNumberish;
    yesToken: AddressLike;
    noToken: AddressLike;
    totalBacking: BigNumberish;
    platformFees: BigNumberish;
    creatorFees: BigNumberish;
    varaStateHash: BytesLike;
  };

  export type MarketStructOutput = [
    creator: string,
    question: string,
    category: string,
    endTime: bigint,
    status: bigint,
    outcome: bigint,
    yesToken: string,
    noToken: string,
    totalBacking: bigint,
    platformFees: bigint,
    creatorFees: bigint,
    varaStateHash: string
  ] & {
    creator: string;
    question: string;
    category: string;
    endTime: bigint;
    status: bigint;
    outcome: bigint;
    yesToken: string;
    noToken: string;
    totalBacking: bigint;
    platformFees: bigint;
    creatorFees: bigint;
    varaStateHash: string;
  };
}

export interface PredictionMarketSettlementInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "CREATOR_FEE_BPS"
      | "PLATFORM_FEE_BPS"
      | "TOTAL_FEE_BPS"
      | "claimRedemption"
      | "createMarket"
      | "deposit"
      | "finalizeTradeFromVara"
      | "finalizeWithdrawalFromVara"
      | "getMarketInfo"
      | "markets"
      | "nextMarketId"
      | "owner"
      | "relayer"
      | "requestWithdrawal"
      | "resolveMarket"
      | "setRelayer"
      | "withdrawPlatformFees"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "DepositMade"
      | "MarketCreated"
      | "MarketResolved"
      | "RedemptionClaimed"
      | "TradeFinalized"
      | "WithdrawalRequested"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "CREATOR_FEE_BPS",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "PLATFORM_FEE_BPS",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "TOTAL_FEE_BPS",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "claimRedemption",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "createMarket",
    values: [string, string, BigNumberish, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "deposit",
    values: [BigNumberish, boolean]
  ): string;
  encodeFunctionData(
    functionFragment: "finalizeTradeFromVara",
    values: [
      BigNumberish,
      AddressLike,
      boolean,
      BigNumberish,
      BigNumberish,
      BigNumberish,
      BigNumberish,
      BytesLike
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "finalizeWithdrawalFromVara",
    values: [
      BigNumberish,
      AddressLike,
      BigNumberish,
      BigNumberish,
      BigNumberish,
      BytesLike
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "getMarketInfo",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "markets",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "nextMarketId",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(functionFragment: "relayer", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "requestWithdrawal",
    values: [BigNumberish, boolean, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "resolveMarket",
    values: [BigNumberish, BigNumberish, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "setRelayer",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "withdrawPlatformFees",
    values: [BigNumberish]
  ): string;

  decodeFunctionResult(
    functionFragment: "CREATOR_FEE_BPS",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "PLATFORM_FEE_BPS",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "TOTAL_FEE_BPS",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "claimRedemption",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "createMarket",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "deposit", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "finalizeTradeFromVara",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "finalizeWithdrawalFromVara",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getMarketInfo",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "markets", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "nextMarketId",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "relayer", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "requestWithdrawal",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "resolveMarket",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "setRelayer", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "withdrawPlatformFees",
    data: BytesLike
  ): Result;
}

export namespace DepositMadeEvent {
  export type InputTuple = [
    marketId: BigNumberish,
    user: AddressLike,
    isYes: boolean,
    amount: BigNumberish,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [
    marketId: bigint,
    user: string,
    isYes: boolean,
    amount: bigint,
    timestamp: bigint
  ];
  export interface OutputObject {
    marketId: bigint;
    user: string;
    isYes: boolean;
    amount: bigint;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace MarketCreatedEvent {
  export type InputTuple = [
    marketId: BigNumberish,
    creator: AddressLike,
    question: string,
    category: string,
    yesToken: AddressLike,
    noToken: AddressLike,
    endTime: BigNumberish,
    initialYes: BigNumberish,
    initialNo: BigNumberish
  ];
  export type OutputTuple = [
    marketId: bigint,
    creator: string,
    question: string,
    category: string,
    yesToken: string,
    noToken: string,
    endTime: bigint,
    initialYes: bigint,
    initialNo: bigint
  ];
  export interface OutputObject {
    marketId: bigint;
    creator: string;
    question: string;
    category: string;
    yesToken: string;
    noToken: string;
    endTime: bigint;
    initialYes: bigint;
    initialNo: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace MarketResolvedEvent {
  export type InputTuple = [
    marketId: BigNumberish,
    outcome: BigNumberish,
    finalStateHash: BytesLike
  ];
  export type OutputTuple = [
    marketId: bigint,
    outcome: bigint,
    finalStateHash: string
  ];
  export interface OutputObject {
    marketId: bigint;
    outcome: bigint;
    finalStateHash: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RedemptionClaimedEvent {
  export type InputTuple = [
    marketId: BigNumberish,
    user: AddressLike,
    amount: BigNumberish
  ];
  export type OutputTuple = [marketId: bigint, user: string, amount: bigint];
  export interface OutputObject {
    marketId: bigint;
    user: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace TradeFinalizedEvent {
  export type InputTuple = [
    marketId: BigNumberish,
    user: AddressLike,
    isYes: boolean,
    amountIn: BigNumberish,
    tokensOut: BigNumberish,
    varaStateHash: BytesLike
  ];
  export type OutputTuple = [
    marketId: bigint,
    user: string,
    isYes: boolean,
    amountIn: bigint,
    tokensOut: bigint,
    varaStateHash: string
  ];
  export interface OutputObject {
    marketId: bigint;
    user: string;
    isYes: boolean;
    amountIn: bigint;
    tokensOut: bigint;
    varaStateHash: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace WithdrawalRequestedEvent {
  export type InputTuple = [
    marketId: BigNumberish,
    user: AddressLike,
    isYes: boolean,
    tokenAmount: BigNumberish,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [
    marketId: bigint,
    user: string,
    isYes: boolean,
    tokenAmount: bigint,
    timestamp: bigint
  ];
  export interface OutputObject {
    marketId: bigint;
    user: string;
    isYes: boolean;
    tokenAmount: bigint;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface PredictionMarketSettlement extends BaseContract {
  connect(runner?: ContractRunner | null): PredictionMarketSettlement;
  waitForDeployment(): Promise<this>;

  interface: PredictionMarketSettlementInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  CREATOR_FEE_BPS: TypedContractMethod<[], [bigint], "view">;

  PLATFORM_FEE_BPS: TypedContractMethod<[], [bigint], "view">;

  TOTAL_FEE_BPS: TypedContractMethod<[], [bigint], "view">;

  claimRedemption: TypedContractMethod<
    [marketId: BigNumberish],
    [void],
    "nonpayable"
  >;

  createMarket: TypedContractMethod<
    [
      question: string,
      category: string,
      endTime: BigNumberish,
      initialYes: BigNumberish,
      initialNo: BigNumberish
    ],
    [bigint],
    "payable"
  >;

  deposit: TypedContractMethod<
    [marketId: BigNumberish, isYes: boolean],
    [void],
    "payable"
  >;

  finalizeTradeFromVara: TypedContractMethod<
    [
      marketId: BigNumberish,
      user: AddressLike,
      isYes: boolean,
      amountIn: BigNumberish,
      tokensOut: BigNumberish,
      creatorFee: BigNumberish,
      platformFee: BigNumberish,
      varaStateHash: BytesLike
    ],
    [void],
    "nonpayable"
  >;

  finalizeWithdrawalFromVara: TypedContractMethod<
    [
      marketId: BigNumberish,
      user: AddressLike,
      ethOut: BigNumberish,
      creatorFee: BigNumberish,
      platformFee: BigNumberish,
      varaStateHash: BytesLike
    ],
    [void],
    "nonpayable"
  >;

  getMarketInfo: TypedContractMethod<
    [marketId: BigNumberish],
    [PredictionMarketSettlement.MarketStructOutput],
    "view"
  >;

  markets: TypedContractMethod<
    [arg0: BigNumberish],
    [
      [
        string,
        string,
        string,
        bigint,
        bigint,
        bigint,
        string,
        string,
        bigint,
        bigint,
        bigint,
        string
      ] & {
        creator: string;
        question: string;
        category: string;
        endTime: bigint;
        status: bigint;
        outcome: bigint;
        yesToken: string;
        noToken: string;
        totalBacking: bigint;
        platformFees: bigint;
        creatorFees: bigint;
        varaStateHash: string;
      }
    ],
    "view"
  >;

  nextMarketId: TypedContractMethod<[], [bigint], "view">;

  owner: TypedContractMethod<[], [string], "view">;

  relayer: TypedContractMethod<[], [string], "view">;

  requestWithdrawal: TypedContractMethod<
    [marketId: BigNumberish, isYes: boolean, tokenAmount: BigNumberish],
    [void],
    "nonpayable"
  >;

  resolveMarket: TypedContractMethod<
    [
      marketId: BigNumberish,
      outcomeIndex: BigNumberish,
      finalStateHash: BytesLike
    ],
    [void],
    "nonpayable"
  >;

  setRelayer: TypedContractMethod<
    [newRelayer: AddressLike],
    [void],
    "nonpayable"
  >;

  withdrawPlatformFees: TypedContractMethod<
    [marketId: BigNumberish],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "CREATOR_FEE_BPS"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "PLATFORM_FEE_BPS"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "TOTAL_FEE_BPS"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "claimRedemption"
  ): TypedContractMethod<[marketId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "createMarket"
  ): TypedContractMethod<
    [
      question: string,
      category: string,
      endTime: BigNumberish,
      initialYes: BigNumberish,
      initialNo: BigNumberish
    ],
    [bigint],
    "payable"
  >;
  getFunction(
    nameOrSignature: "deposit"
  ): TypedContractMethod<
    [marketId: BigNumberish, isYes: boolean],
    [void],
    "payable"
  >;
  getFunction(
    nameOrSignature: "finalizeTradeFromVara"
  ): TypedContractMethod<
    [
      marketId: BigNumberish,
      user: AddressLike,
      isYes: boolean,
      amountIn: BigNumberish,
      tokensOut: BigNumberish,
      creatorFee: BigNumberish,
      platformFee: BigNumberish,
      varaStateHash: BytesLike
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "finalizeWithdrawalFromVara"
  ): TypedContractMethod<
    [
      marketId: BigNumberish,
      user: AddressLike,
      ethOut: BigNumberish,
      creatorFee: BigNumberish,
      platformFee: BigNumberish,
      varaStateHash: BytesLike
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "getMarketInfo"
  ): TypedContractMethod<
    [marketId: BigNumberish],
    [PredictionMarketSettlement.MarketStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "markets"
  ): TypedContractMethod<
    [arg0: BigNumberish],
    [
      [
        string,
        string,
        string,
        bigint,
        bigint,
        bigint,
        string,
        string,
        bigint,
        bigint,
        bigint,
        string
      ] & {
        creator: string;
        question: string;
        category: string;
        endTime: bigint;
        status: bigint;
        outcome: bigint;
        yesToken: string;
        noToken: string;
        totalBacking: bigint;
        platformFees: bigint;
        creatorFees: bigint;
        varaStateHash: string;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "nextMarketId"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "relayer"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "requestWithdrawal"
  ): TypedContractMethod<
    [marketId: BigNumberish, isYes: boolean, tokenAmount: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "resolveMarket"
  ): TypedContractMethod<
    [
      marketId: BigNumberish,
      outcomeIndex: BigNumberish,
      finalStateHash: BytesLike
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "setRelayer"
  ): TypedContractMethod<[newRelayer: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "withdrawPlatformFees"
  ): TypedContractMethod<[marketId: BigNumberish], [void], "nonpayable">;

  getEvent(
    key: "DepositMade"
  ): TypedContractEvent<
    DepositMadeEvent.InputTuple,
    DepositMadeEvent.OutputTuple,
    DepositMadeEvent.OutputObject
  >;
  getEvent(
    key: "MarketCreated"
  ): TypedContractEvent<
    MarketCreatedEvent.InputTuple,
    MarketCreatedEvent.OutputTuple,
    MarketCreatedEvent.OutputObject
  >;
  getEvent(
    key: "MarketResolved"
  ): TypedContractEvent<
    MarketResolvedEvent.InputTuple,
    MarketResolvedEvent.OutputTuple,
    MarketResolvedEvent.OutputObject
  >;
  getEvent(
    key: "RedemptionClaimed"
  ): TypedContractEvent<
    RedemptionClaimedEvent.InputTuple,
    RedemptionClaimedEvent.OutputTuple,
    RedemptionClaimedEvent.OutputObject
  >;
  getEvent(
    key: "TradeFinalized"
  ): TypedContractEvent<
    TradeFinalizedEvent.InputTuple,
    TradeFinalizedEvent.OutputTuple,
    TradeFinalizedEvent.OutputObject
  >;
  getEvent(
    key: "WithdrawalRequested"
  ): TypedContractEvent<
    WithdrawalRequestedEvent.InputTuple,
    WithdrawalRequestedEvent.OutputTuple,
    WithdrawalRequestedEvent.OutputObject
  >;

  filters: {
    "DepositMade(uint256,address,bool,uint256,uint256)": TypedContractEvent<
      DepositMadeEvent.InputTuple,
      DepositMadeEvent.OutputTuple,
      DepositMadeEvent.OutputObject
    >;
    DepositMade: TypedContractEvent<
      DepositMadeEvent.InputTuple,
      DepositMadeEvent.OutputTuple,
      DepositMadeEvent.OutputObject
    >;

    "MarketCreated(uint256,address,string,string,address,address,uint256,uint256,uint256)": TypedContractEvent<
      MarketCreatedEvent.InputTuple,
      MarketCreatedEvent.OutputTuple,
      MarketCreatedEvent.OutputObject
    >;
    MarketCreated: TypedContractEvent<
      MarketCreatedEvent.InputTuple,
      MarketCreatedEvent.OutputTuple,
      MarketCreatedEvent.OutputObject
    >;

    "MarketResolved(uint256,uint8,bytes32)": TypedContractEvent<
      MarketResolvedEvent.InputTuple,
      MarketResolvedEvent.OutputTuple,
      MarketResolvedEvent.OutputObject
    >;
    MarketResolved: TypedContractEvent<
      MarketResolvedEvent.InputTuple,
      MarketResolvedEvent.OutputTuple,
      MarketResolvedEvent.OutputObject
    >;

    "RedemptionClaimed(uint256,address,uint256)": TypedContractEvent<
      RedemptionClaimedEvent.InputTuple,
      RedemptionClaimedEvent.OutputTuple,
      RedemptionClaimedEvent.OutputObject
    >;
    RedemptionClaimed: TypedContractEvent<
      RedemptionClaimedEvent.InputTuple,
      RedemptionClaimedEvent.OutputTuple,
      RedemptionClaimedEvent.OutputObject
    >;

    "TradeFinalized(uint256,address,bool,uint256,uint256,bytes32)": TypedContractEvent<
      TradeFinalizedEvent.InputTuple,
      TradeFinalizedEvent.OutputTuple,
      TradeFinalizedEvent.OutputObject
    >;
    TradeFinalized: TypedContractEvent<
      TradeFinalizedEvent.InputTuple,
      TradeFinalizedEvent.OutputTuple,
      TradeFinalizedEvent.OutputObject
    >;

    "WithdrawalRequested(uint256,address,bool,uint256,uint256)": TypedContractEvent<
      WithdrawalRequestedEvent.InputTuple,
      WithdrawalRequestedEvent.OutputTuple,
      WithdrawalRequestedEvent.OutputObject
    >;
    WithdrawalRequested: TypedContractEvent<
      WithdrawalRequestedEvent.InputTuple,
      WithdrawalRequestedEvent.OutputTuple,
      WithdrawalRequestedEvent.OutputObject
    >;
  };
}
