/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { IVaraEthMirror } from "./IVaraEthMirror";
export type { PredictionMarketSettlementVaraEth } from "./PredictionMarketSettlementVaraEth";
