/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export declare namespace PredictionMarketSettlementVaraEth {
  export type MarketStruct = {
    creator: AddressLike;
    question: string;
    category: string;
    endTime: BigNumberish;
    status: BigNumberish;
    outcome: BigNumberish;
    yesToken: AddressLike;
    noToken: AddressLike;
    totalBacking: BigNumberish;
    platformFees: BigNumberish;
    creatorFees: BigNumberish;
    lastStateHash: BytesLike;
  };

  export type MarketStructOutput = [
    creator: string,
    question: string,
    category: string,
    endTime: bigint,
    status: bigint,
    outcome: bigint,
    yesToken: string,
    noToken: string,
    totalBacking: bigint,
    platformFees: bigint,
    creatorFees: bigint,
    lastStateHash: string
  ] & {
    creator: string;
    question: string;
    category: string;
    endTime: bigint;
    status: bigint;
    outcome: bigint;
    yesToken: string;
    noToken: string;
    totalBacking: bigint;
    platformFees: bigint;
    creatorFees: bigint;
    lastStateHash: string;
  };
}

export interface PredictionMarketSettlementVaraEthInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "CREATOR_FEE_BPS"
      | "PLATFORM_FEE_BPS"
      | "TOTAL_FEE_BPS"
      | "claimRedemption"
      | "createMarket"
      | "deposit"
      | "getMarketInfo"
      | "getStateHash"
      | "marketEngineMirror"
      | "markets"
      | "nextMarketId"
      | "owner"
      | "requestWithdrawal"
      | "resolveMarket"
      | "withdrawPlatformFees"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "MarketCreated"
      | "MarketResolved"
      | "RedemptionClaimed"
      | "TradeExecuted"
      | "WithdrawalProcessed"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "CREATOR_FEE_BPS",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "PLATFORM_FEE_BPS",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "TOTAL_FEE_BPS",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "claimRedemption",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "createMarket",
    values: [string, string, BigNumberish, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "deposit",
    values: [BigNumberish, boolean]
  ): string;
  encodeFunctionData(
    functionFragment: "getMarketInfo",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getStateHash",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "marketEngineMirror",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "markets",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "nextMarketId",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "requestWithdrawal",
    values: [BigNumberish, boolean, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "resolveMarket",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "withdrawPlatformFees",
    values: [BigNumberish]
  ): string;

  decodeFunctionResult(
    functionFragment: "CREATOR_FEE_BPS",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "PLATFORM_FEE_BPS",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "TOTAL_FEE_BPS",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "claimRedemption",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "createMarket",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "deposit", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getMarketInfo",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getStateHash",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "marketEngineMirror",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "markets", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "nextMarketId",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "requestWithdrawal",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "resolveMarket",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "withdrawPlatformFees",
    data: BytesLike
  ): Result;
}

export namespace MarketCreatedEvent {
  export type InputTuple = [
    marketId: BigNumberish,
    creator: AddressLike,
    question: string,
    category: string,
    yesToken: AddressLike,
    noToken: AddressLike,
    endTime: BigNumberish,
    initialYes: BigNumberish,
    initialNo: BigNumberish
  ];
  export type OutputTuple = [
    marketId: bigint,
    creator: string,
    question: string,
    category: string,
    yesToken: string,
    noToken: string,
    endTime: bigint,
    initialYes: bigint,
    initialNo: bigint
  ];
  export interface OutputObject {
    marketId: bigint;
    creator: string;
    question: string;
    category: string;
    yesToken: string;
    noToken: string;
    endTime: bigint;
    initialYes: bigint;
    initialNo: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace MarketResolvedEvent {
  export type InputTuple = [
    marketId: BigNumberish,
    outcome: BigNumberish,
    finalStateHash: BytesLike
  ];
  export type OutputTuple = [
    marketId: bigint,
    outcome: bigint,
    finalStateHash: string
  ];
  export interface OutputObject {
    marketId: bigint;
    outcome: bigint;
    finalStateHash: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RedemptionClaimedEvent {
  export type InputTuple = [
    marketId: BigNumberish,
    user: AddressLike,
    amount: BigNumberish
  ];
  export type OutputTuple = [marketId: bigint, user: string, amount: bigint];
  export interface OutputObject {
    marketId: bigint;
    user: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace TradeExecutedEvent {
  export type InputTuple = [
    marketId: BigNumberish,
    user: AddressLike,
    isYes: boolean,
    amountIn: BigNumberish,
    tokensOut: BigNumberish,
    stateHash: BytesLike
  ];
  export type OutputTuple = [
    marketId: bigint,
    user: string,
    isYes: boolean,
    amountIn: bigint,
    tokensOut: bigint,
    stateHash: string
  ];
  export interface OutputObject {
    marketId: bigint;
    user: string;
    isYes: boolean;
    amountIn: bigint;
    tokensOut: bigint;
    stateHash: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace WithdrawalProcessedEvent {
  export type InputTuple = [
    marketId: BigNumberish,
    user: AddressLike,
    ethOut: BigNumberish,
    stateHash: BytesLike
  ];
  export type OutputTuple = [
    marketId: bigint,
    user: string,
    ethOut: bigint,
    stateHash: string
  ];
  export interface OutputObject {
    marketId: bigint;
    user: string;
    ethOut: bigint;
    stateHash: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface PredictionMarketSettlementVaraEth extends BaseContract {
  connect(runner?: ContractRunner | null): PredictionMarketSettlementVaraEth;
  waitForDeployment(): Promise<this>;

  interface: PredictionMarketSettlementVaraEthInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  CREATOR_FEE_BPS: TypedContractMethod<[], [bigint], "view">;

  PLATFORM_FEE_BPS: TypedContractMethod<[], [bigint], "view">;

  TOTAL_FEE_BPS: TypedContractMethod<[], [bigint], "view">;

  claimRedemption: TypedContractMethod<
    [marketId: BigNumberish],
    [void],
    "nonpayable"
  >;

  createMarket: TypedContractMethod<
    [
      question: string,
      category: string,
      endTime: BigNumberish,
      initialYes: BigNumberish,
      initialNo: BigNumberish
    ],
    [bigint],
    "payable"
  >;

  deposit: TypedContractMethod<
    [marketId: BigNumberish, isYes: boolean],
    [void],
    "payable"
  >;

  getMarketInfo: TypedContractMethod<
    [marketId: BigNumberish],
    [PredictionMarketSettlementVaraEth.MarketStructOutput],
    "view"
  >;

  getStateHash: TypedContractMethod<[], [string], "view">;

  marketEngineMirror: TypedContractMethod<[], [string], "view">;

  markets: TypedContractMethod<
    [arg0: BigNumberish],
    [
      [
        string,
        string,
        string,
        bigint,
        bigint,
        bigint,
        string,
        string,
        bigint,
        bigint,
        bigint,
        string
      ] & {
        creator: string;
        question: string;
        category: string;
        endTime: bigint;
        status: bigint;
        outcome: bigint;
        yesToken: string;
        noToken: string;
        totalBacking: bigint;
        platformFees: bigint;
        creatorFees: bigint;
        lastStateHash: string;
      }
    ],
    "view"
  >;

  nextMarketId: TypedContractMethod<[], [bigint], "view">;

  owner: TypedContractMethod<[], [string], "view">;

  requestWithdrawal: TypedContractMethod<
    [marketId: BigNumberish, isYes: boolean, tokenAmount: BigNumberish],
    [void],
    "nonpayable"
  >;

  resolveMarket: TypedContractMethod<
    [marketId: BigNumberish, outcomeIndex: BigNumberish],
    [void],
    "nonpayable"
  >;

  withdrawPlatformFees: TypedContractMethod<
    [marketId: BigNumberish],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "CREATOR_FEE_BPS"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "PLATFORM_FEE_BPS"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "TOTAL_FEE_BPS"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "claimRedemption"
  ): TypedContractMethod<[marketId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "createMarket"
  ): TypedContractMethod<
    [
      question: string,
      category: string,
      endTime: BigNumberish,
      initialYes: BigNumberish,
      initialNo: BigNumberish
    ],
    [bigint],
    "payable"
  >;
  getFunction(
    nameOrSignature: "deposit"
  ): TypedContractMethod<
    [marketId: BigNumberish, isYes: boolean],
    [void],
    "payable"
  >;
  getFunction(
    nameOrSignature: "getMarketInfo"
  ): TypedContractMethod<
    [marketId: BigNumberish],
    [PredictionMarketSettlementVaraEth.MarketStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "getStateHash"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "marketEngineMirror"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "markets"
  ): TypedContractMethod<
    [arg0: BigNumberish],
    [
      [
        string,
        string,
        string,
        bigint,
        bigint,
        bigint,
        string,
        string,
        bigint,
        bigint,
        bigint,
        string
      ] & {
        creator: string;
        question: string;
        category: string;
        endTime: bigint;
        status: bigint;
        outcome: bigint;
        yesToken: string;
        noToken: string;
        totalBacking: bigint;
        platformFees: bigint;
        creatorFees: bigint;
        lastStateHash: string;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "nextMarketId"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "requestWithdrawal"
  ): TypedContractMethod<
    [marketId: BigNumberish, isYes: boolean, tokenAmount: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "resolveMarket"
  ): TypedContractMethod<
    [marketId: BigNumberish, outcomeIndex: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "withdrawPlatformFees"
  ): TypedContractMethod<[marketId: BigNumberish], [void], "nonpayable">;

  getEvent(
    key: "MarketCreated"
  ): TypedContractEvent<
    MarketCreatedEvent.InputTuple,
    MarketCreatedEvent.OutputTuple,
    MarketCreatedEvent.OutputObject
  >;
  getEvent(
    key: "MarketResolved"
  ): TypedContractEvent<
    MarketResolvedEvent.InputTuple,
    MarketResolvedEvent.OutputTuple,
    MarketResolvedEvent.OutputObject
  >;
  getEvent(
    key: "RedemptionClaimed"
  ): TypedContractEvent<
    RedemptionClaimedEvent.InputTuple,
    RedemptionClaimedEvent.OutputTuple,
    RedemptionClaimedEvent.OutputObject
  >;
  getEvent(
    key: "TradeExecuted"
  ): TypedContractEvent<
    TradeExecutedEvent.InputTuple,
    TradeExecutedEvent.OutputTuple,
    TradeExecutedEvent.OutputObject
  >;
  getEvent(
    key: "WithdrawalProcessed"
  ): TypedContractEvent<
    WithdrawalProcessedEvent.InputTuple,
    WithdrawalProcessedEvent.OutputTuple,
    WithdrawalProcessedEvent.OutputObject
  >;

  filters: {
    "MarketCreated(uint256,address,string,string,address,address,uint256,uint256,uint256)": TypedContractEvent<
      MarketCreatedEvent.InputTuple,
      MarketCreatedEvent.OutputTuple,
      MarketCreatedEvent.OutputObject
    >;
    MarketCreated: TypedContractEvent<
      MarketCreatedEvent.InputTuple,
      MarketCreatedEvent.OutputTuple,
      MarketCreatedEvent.OutputObject
    >;

    "MarketResolved(uint256,uint8,bytes32)": TypedContractEvent<
      MarketResolvedEvent.InputTuple,
      MarketResolvedEvent.OutputTuple,
      MarketResolvedEvent.OutputObject
    >;
    MarketResolved: TypedContractEvent<
      MarketResolvedEvent.InputTuple,
      MarketResolvedEvent.OutputTuple,
      MarketResolvedEvent.OutputObject
    >;

    "RedemptionClaimed(uint256,address,uint256)": TypedContractEvent<
      RedemptionClaimedEvent.InputTuple,
      RedemptionClaimedEvent.OutputTuple,
      RedemptionClaimedEvent.OutputObject
    >;
    RedemptionClaimed: TypedContractEvent<
      RedemptionClaimedEvent.InputTuple,
      RedemptionClaimedEvent.OutputTuple,
      RedemptionClaimedEvent.OutputObject
    >;

    "TradeExecuted(uint256,address,bool,uint256,uint256,bytes32)": TypedContractEvent<
      TradeExecutedEvent.InputTuple,
      TradeExecutedEvent.OutputTuple,
      TradeExecutedEvent.OutputObject
    >;
    TradeExecuted: TypedContractEvent<
      TradeExecutedEvent.InputTuple,
      TradeExecutedEvent.OutputTuple,
      TradeExecutedEvent.OutputObject
    >;

    "WithdrawalProcessed(uint256,address,uint256,bytes32)": TypedContractEvent<
      WithdrawalProcessedEvent.InputTuple,
      WithdrawalProcessedEvent.OutputTuple,
      WithdrawalProcessedEvent.OutputObject
    >;
    WithdrawalProcessed: TypedContractEvent<
      WithdrawalProcessedEvent.InputTuple,
      WithdrawalProcessedEvent.OutputTuple,
      WithdrawalProcessedEvent.OutputObject
    >;
  };
}
