/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { IVaraEthMirror__factory } from "./IVaraEthMirror__factory";
export { PredictionMarketSettlementVaraEth__factory } from "./PredictionMarketSettlementVaraEth__factory";
