/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  IVaraEthMirror,
  IVaraEthMirrorInterface,
} from "../../PredictionMarketSettlementVaraEth.sol/IVaraEthMirror";

const _abi = [
  {
    inputs: [
      {
        internalType: "bytes",
        name: "payload",
        type: "bytes",
      },
      {
        internalType: "bool",
        name: "callReply",
        type: "bool",
      },
    ],
    name: "sendMessage",
    outputs: [
      {
        internalType: "bytes32",
        name: "",
        type: "bytes32",
      },
    ],
    stateMutability: "payable",
    type: "function",
  },
  {
    inputs: [],
    name: "stateHash",
    outputs: [
      {
        internalType: "bytes32",
        name: "",
        type: "bytes32",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
] as const;

export class IVaraEthMirror__factory {
  static readonly abi = _abi;
  static createInterface(): IVaraEthMirrorInterface {
    return new Interface(_abi) as IVaraEthMirrorInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): IVaraEthMirror {
    return new Contract(address, _abi, runner) as unknown as IVaraEthMirror;
  }
}
